var document=[
{NAME:"louie sanders    ",PRE-FILLED FIELD:"PRE-FILLED FIELD",PRE-FILLED FIELD:"",PRE-FILLED FIELD:""},
{NAME:"bert hansson    ",PRE-FILLED FIELD:"PRE-FILLED FIELD",PRE-FILLED FIELD:"",PRE-FILLED FIELD:""},
{NAME:"linda masterson    ",PRE-FILLED FIELD:"PRE-FILLED FIELD",PRE-FILLED FIELD:"",PRE-FILLED FIELD:""},
{NAME:"hanna star    ",PRE-FILLED FIELD:"PRE-FILLED FIELD",PRE-FILLED FIELD:"",PRE-FILLED FIELD:""},
];
db.YOUR_COLLECTION.insert(document);
